

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/managedb?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 134525
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8001
mybatis:
    mapper-locations: classpath:mybatis/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/demo/files/